// Lens Correction for Safelight — MIT licensed (see LICENSE).
// Metadata-only Fujifilm GFX100RF RAF (1172 bytes): the camera's real 148-byte
// header with the JPEG and CFA-header regions emptied, followed by the first
// 1024 bytes of the real CFA section (TIFF header, Fujifilm sub-IFD and its
// correction tables). The raw strip starts at CFA offset 2048, so no image data
// is included.

export const GFX100RF_META_RAF_BASE64 = [
  "RlVKSUZJTE1DQ0QtUkFXIDAyMDFGRjE4OTUwNUdGWDEwMFJGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDExMgAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAlAAAAAAAAACUAAAAAAAAAJQAAAQAAAAAAgb50aAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAElJKgAIAAAAAQAA8A0AAQAAABoAAAAAAAAAFAAB8AQAAQAAACAuAAAC8AQAAQAAADIiAAAD8AQAAQAAABAAAAAE8AQA",
  "AQAAAAAAAAAF8AQAAQAAAAAAAAAG8AQAAQAAAAAAAAAH8AQAAQAAAAAIAAAI8AQAAQAAAKDJ+QYJ8AQAAQAAAAAAAAAK8AQA",
  "BAAAABABAAAL8AoAEwAAACABAAAM8AQACAAAALgBAAAN8AQAAwAAANgBAAAO8AQAAwAAAOQBAAAP8AoAHQAAAPABAAAQ8AoA",
  "EwAAANACAAAR8AkAAQAAAAAAAAAS8AkAAQAAAAAAAAAT8AQAAwAAAGgDAAAU8AQAAwAAAHQDAAAAAAAA/w8AAP8PAAD/DwAA",
  "/w8AAHAcAAAJAAAAxwMAAK8KAABYBQAArwoAAIsGAACvCgAAjgcAAK8KAAByCAAArwoAAEEJAACvCgAA/gkAAK8KAACvCgAA",
  "rwoAAFULAACvCgAApOL+/wAAAQAkqv3/AAABAKRx/P8AAAEAa0P7/wAAAQC5Gfr/AAABAE76+P8AAAEASuL3/wAAAQAk1Pb/",
  "AAABAOPm9f8AAAEALgEAAGQBAABdAwAAEQAAAC4BAABlAgAA6QEAABUAAAAuAQAADAIAAEICAAAuAQAADAIAAEICAABwHAAA",
  "CQAAAMcDAACvCgAAWAUAAK8KAACLBgAArwoAAI4HAACvCgAAcggAAK8KAABBCQAArwoAAP4JAACvCgAArwoAAK8KAABVCwAA",
  "rwoAAAcAAAAAAAEABQAAAAAAAQAFAAAAAAABAAYAAAAAAAEABgAAAAAAAQAEAAAAAAABAAAAAAAAAAEA/f///wAAAQD9////",
  "AAABAAUAAAAAAAEABgAAAAAAAQAGAAAAAAABAAYAAAAAAAEACAAAAAAAAQAKAAAAAAABAA0AAAAAAAEAEwAAAAAAAQATAAAA",
  "AAABAHAcAAAJAAAAxwMAAK8KAABYBQAArwoAAIsGAACvCgAAjgcAAK8KAAByCAAArwoAAEEJAACvCgAA/gkAAK8KAACvCgAA",
  "rwoAAFULAACvCgAAFeoCAAAIAACZswIAAAgAAICBAgAACAAAH1ACAAAIAACXIwIAAAgAAAf8AQAACAAAqdkBAAAIAABVugEA",
  "AAgAAFW6AQAACAAALgEAAAwCAABCAgAALgEAAOUBAACDAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAA=",
].join("");
